# Generated by Django 4.1.7 on 2023-03-02 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_movie_update_att'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='update_att',
            new_name='updated_att',
        ),
    ]
